import React from 'react'

function getRiskLevel(probability) {
  const p = Number(probability || 0)

  if (p >= 70) return 'CRITICAL'
  if (p >= 50) return 'HIGH'
  if (p >= 30) return 'MEDIUM'
  return 'LOW'
}

export default function DashboardOverview({ zones = [], alerts = [], health = null }) {
  const levels = zones.map((z) =>
    getRiskLevel(z.probability ?? z.risk_probability)
  )

  const critical = levels.filter((x) => x === 'CRITICAL').length
  const high = levels.filter((x) => x === 'HIGH').length
  const medium = levels.filter((x) => x === 'MEDIUM').length

  const activeRiskZones = critical + high

  const backendOnline =
    health !== null &&
    (
      health?.status === 'ok' ||
      health?.status === 'healthy' ||
      health?.healthy === true ||
      health === true
    )

  return (
    <div className="professional-dashboard">

      <div className="dashboard-topbar">
        <div>
          <div className="dashboard-brand">LREWS</div>
          <div className="dashboard-subtitle">
            Landslide Risk & Early Warning System
          </div>
        </div>

        <div className="dashboard-status-group">

          <div className="risk-counter critical">
            <strong>{critical}</strong>
            <span>CRITICAL</span>
          </div>

          <div className="risk-counter warning">
            <strong>{high}</strong>
            <span>WARNING</span>
          </div>

          <div className="risk-counter medium">
            <strong>{medium}</strong>
            <span>MEDIUM</span>
          </div>

        </div>
      </div>

      <div className="situation-title">
        <span className="title-line" />
        <h2>SITUATION OVERVIEW</h2>
        <span>North Eastern Region · India</span>
      </div>

      <div className="overview-grid">

        <div className="overview-card danger">
          <div className="card-label">ACTIVE RISK ZONES</div>
          <div className="card-number">{activeRiskZones}</div>
          <div className="card-description">
            High + Critical risk locations
          </div>
        </div>

        <div className="overview-card warning">
          <div className="card-label">MONITORED ZONES</div>
          <div className="card-number">{zones.length}</div>
          <div className="card-description">
            Locations currently monitored
          </div>
        </div>

        <div className="overview-card people">
          <div className="card-label">MEDIUM RISK ZONES</div>
          <div className="card-number">{medium}</div>
          <div className="card-description">
            Locations requiring observation
          </div>
        </div>

        <div className="overview-card alerts">
          <div className="card-label">ACTIVE ALERTS</div>
          <div className="card-number">{alerts.length}</div>
          <div className="card-description">
            Alerts generated by the system
          </div>
        </div>

      </div>

      <div className="system-panel">

        <div className="system-panel-title">
          SYSTEM STATUS
        </div>

        <div className="system-status-grid">

          <div className="system-status-item">
            <span>Backend API</span>
            <strong className={backendOnline ? 'online' : 'offline'}>
              ● {backendOnline ? 'ONLINE' : 'OFFLINE'}
            </strong>
          </div>

          <div className="system-status-item">
            <span>ML Risk Model</span>
            <strong className="online">
              ● ONLINE
            </strong>
          </div>

          <div className="system-status-item">
            <span>Weather Service</span>
            <strong className="online">
              ● LIVE
            </strong>
          </div>

          <div className="system-status-item">
            <span>Risk Monitoring</span>
            <strong className="online">
              ● ACTIVE
            </strong>
          </div>

        </div>
      </div>

      <div className="ai-summary">

        <div>
          <div className="ai-summary-title">
            AI RISK SUMMARY
          </div>

          <div className="ai-summary-text">

            {critical > 0
              ? `${critical} location${critical > 1 ? 's are' : ' is'} currently classified as CRITICAL risk. Immediate monitoring is recommended.`
              : high > 0
                ? `${high} high-risk location${high > 1 ? 's are' : ' is'} currently being monitored.`
                : 'No critical or high-risk locations detected at this time.'
            }

          </div>
        </div>

        <div className="ai-badge">
          AI
        </div>

      </div>

    </div>
  )
}
